### ISSUE TITLE
# Missing: zh_CN.UTF-8/UTF-8 \ main branch and 22.9 are the same

### ISSUE THREAD

**Issue by gnuhub** [endeavouros-team/EndeavourOS-ISO#35]
i build the iso from main and 22.9
offline install 

```
cat /etc/locale.gen 
```
```
# Locales enabled by Calamares
zh_CN.UTF-8 UTF-8
# Missing: zh_CN.UTF-8/UTF-8 \
```

**Comment by killajoe** [comment]
this is caused by latest changes on glibc where arch now ships an unparsed  /usr/share/i18n/SUPPORTED file mit was not there before and calamares using this if present.. it will be resolved soon with the next package update but currently i do use:
```
# TEMPORARY CUSTOM FIXES
# fix locale (glibc) ship unparsed SUPPORTED file
rm /usr/share/i18n/SUPPORTED
```
in run_before_squashfs to remove that file from live session..
