### ISSUE TITLE
please add a comment to /etc/skel/.bashrc

### ISSUE THREAD

**Issue by masavini** [endeavouros-team/EndeavourOS-ISO#48]
could you please add a comment to explain this line of `/etc/skel/.bashrc`?
```sh
[[ "$(whoami)" = "root" ]] && return
```
i usually link `/root/.bashrc` to `/home/me/.bashrc` and i'm just curious about that.

thanks!

**Comment by killajoe** [comment]
@manuel-192 ?

**Comment by killajoe** [comment]
Is this even something on the live ISO? More like on your installed system I bet.


And part of an if do that context inside the bashrc.

**Comment by manuel-192** [comment]
Sorry for the late reply.

First, it is not a good idea to link .bashrc from root to less privileged user because it could cause serious security issues.

That line simply stops reading of .bashrc for user root since typically root does not need the stuff after that line. Often root's .bashrc has much less code.
And all users are more or less expected to adjust .bashrc to their liking.

**Comment by masavini** [comment]
thank you for the explanation!
