### ISSUE TITLE
@killerjoe @dalto8

### ISSUE THREAD

**Issue by rudy-in** [endeavouros-team/EndeavourOS-ISO#55]
Hey there endeavour os team , greetings 
i am an endeavour os user for the past 5 years and i would like contribute to it heres what i can do:

<hr> 
**Kernel development**: i can make a amazing kernel for the OS having zen and lts support on top of that i can also make it a bit of a hardened
**Graphics designing**: although you have hired a gfx designer recently you can always use me as a backup i am always there to do stuff.

**Comment by dalto8** [comment]
Thanks for the offer for assistance!

I don't think that carrying custom kernels is in-line with our current direction.

However, we often need additional help with art so that offer is appreciated.

We are also working on building a list of tasks that need to be done.  As that list grows it would be great for people to take a look at those items and pitch in wherever they feel comfortable.

**Comment by rudy-in** [comment]
thank you dalto8 for replying if you wanna contact me i am on discord as rudy.in and on email i am atsharma623@gmail.com , although carrying out with custom kernel can be beneficial for the OS to add external security and external device support which arch doesn't support
